#!/bin/bash
#SBATCH -A m4025_g
#SBATCH -C gpu
#SBATCH -q regular_ss11
# #SBATCH -t 5:00
#SBATCH -t 4:00:00
#SBATCH -N 1
#SBATCH -o multiTrain.o%j


# run with up to 4 total trainings at once 4 gpus per node
echo "STARTING"
for DIR in seed*/; do
    cd $DIR
    srun --exact -n 1 --gpu-bind=none --gpus-per-task 1 -c 16 --mem-per-cpu=3gb --hint=nomultithread \
    dp train input.json --init-frz-model frozenModel.pb &
    cd ..

done

wait

touch doneTrainingFlag

echo 'DONE RUNNING!!'